# to debug use docker run --rm -it 044e1532c690 sh (044e1532c690 would be the last successfully created image layer)

version: '3'

networks:
 inception: {}

volumes:
 html: {}
 mariadb_data:
  driver_opts:
   type: none
   device: ${DATA_PATH}mariadb
   o: bind
 wordpress_data:
  driver_opts:
   type: none
   device: ${DATA_PATH}wordpress
   o: bind

services:
 nginx:
  build: ${REQUIREMENTS_PATH}/nginx
  ports:
   - 443:443
  container_name: NGINX
  networks:
   - inception
  volumes:
   - wordpress_data:/var/www/html
  depends_on:
   - wordpress
  restart: unless-stopped

 mariadb:
  build:
   context: ${REQUIREMENTS_PATH}/mariadb
   args:
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  ports:
   - 3306:3306
  container_name: MARIADB
  networks:
   - inception
  volumes:
   - mariadb_data:/var/lib/mysql
  restart: unless-stopped


 wordpress:
  build: ${REQUIREMENTS_PATH}/wordpress
  ports:
   - 9000:9000
  container_name: WORDPRESS
  networks:
   - inception
  volumes:
   - wordpress_data:/var/www/html
  depends_on:
   - mariadb
  environment:
   - DB_HOST=${DB_HOST}
   - DB_NAME=${DB_NAME}
   - DB_USER=${DB_USER}
   - DB_USER_PASSWORD=${DB_USER_PASSWORD}
   - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
   - WP_TITLE=${WP_TITLE}
   - WP_URL=${WP_URL}
   - WP_USER=${WP_USER}
   - WP_USER_MAIL=${WP_USER_MAIL}
   - WP_USER_PASSWORD=${WP_USER_PASSWORD}
   - WP_ADMIN=${WP_ADMIN}
   - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
   - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
  restart: unless-stopped