version: '3'

networks:
 inception: {}

volumes:
 mariadb_data:
  driver_opts:
   type: none
   device: ${DB_DATA_PATH}
   o: bind
 wordpress_data:
  driver_opts:
   type: none
   device: ${WP_DATA_PATH}
   o: bind

services:
 nginx:
  build:
   context: ${REQUIREMENTS_PATH}/nginx
   args:
    - CERT=${CERT}
    - KEY=${KEY}
    - DOMAIN_NAME=${DOMAIN_NAME}
  ports:
   - ${NGINX_PORT}:${NGINX_PORT}
  image: ${NGINX_IMAGE_NAME}
  container_name: ${NGINX_CONTAINER_NAME}
  networks:
   - ${NETWORK}
  volumes:
   - wordpress_data:${WP_VOLUME}
  depends_on:
   - wordpress
  restart: unless-stopped

 mariadb:
  build:
   context: ${REQUIREMENTS_PATH}/mariadb
   args:
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  ports:
   - ${MARIADB_PORT}:${MARIADB_PORT}
  image: ${MARIADB_IMAGE_NAME}
  container_name: ${MARIADB_CONTAINER_NAME}
  networks:
   - ${NETWORK}
  volumes:
   - mariadb_data:${DB_VOLUME}
  restart: unless-stopped


 wordpress:
  build:
   context: ${REQUIREMENTS_PATH}/wordpress
   args:
    - WP_VOLUME=${WP_VOLUME}
  ports:
   - ${WORDPRESS_PORT}:${WORDPRESS_PORT}
  image: ${WORDPRESS_IMAGE_NAME}
  container_name: ${WORDPRESS_CONTAINER_NAME}
  networks:
   - ${NETWORK}
  volumes:
   - wordpress_data:${WP_VOLUME}
  depends_on:
   - mariadb
  environment:
   - DB_HOST=${DB_HOST}
   - DB_NAME=${DB_NAME}
   - DB_USER=${DB_USER}
   - DB_USER_PASSWORD=${DB_USER_PASSWORD}
   - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
   - WP_VOLUME=${WP_VOLUME}
   - WP_TITLE=${WP_TITLE}
   - WP_URL=${WP_URL}
   - WP_USER=${WP_USER}
   - WP_USER_MAIL=${WP_USER_MAIL}
   - WP_USER_PASSWORD=${WP_USER_PASSWORD}
   - WP_ADMIN=${WP_ADMIN}
   - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
   - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
  restart: unless-stopped
