version: '3'
volumes:
 html: {}
services:
 nginx:
  build: ./requirements/nginx
  ports:
   - 443:443
  volumes:
   - ./requirements/nginx/html:/usr/share/nginx/html
  environment:
   - NGINX_TEST_ENV=true