version: '3'

networks:
 inception: {}

volumes:
# html: {}
 mariadb_data:
  driver_opts:
   type: none
   device: ${DB_DATA_PATH}
   o: bind
 wordpress_data:
  driver_opts:
   type: none
   device: ${WP_DATA_PATH}
   o: bind

services:
 nginx:
  build: ${REQUIREMENTS_PATH}/nginx
  ports:
   - ${NGINX_PORT}:${NGINX_PORT}
  container_name: ${NGINX_CONTAINER_NAME}
  networks:
   - ${NETWORK}
  volumes:
   - wordpress_data:${WP_VOLUME}
  depends_on:
   - wordpress
  restart: unless-stopped

 mariadb:
  build:
   context: ${REQUIREMENTS_PATH}/mariadb
   args:
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  ports:
   - ${MARIADB_PORT}:${MARIADB_PORT}
  container_name: ${MARIADB_CONTAINER_NAME}
  networks:
   - ${NETWORK}
  volumes:
   - mariadb_data:${DB_VOLUME}
  restart: unless-stopped


 wordpress:
  build: ${REQUIREMENTS_PATH}/wordpress
  ports:
   - ${WORDPRESS_PORT}:${WORDPRESS_PORT}
  container_name: ${WORDPRESS_CONTAINER_NAME}
  networks:
   - ${NETWORK}
  volumes:
   - wordpress_data:${WP_VOLUME}
  depends_on:
   - mariadb
  environment:
   - DB_HOST=${DB_HOST}
   - DB_NAME=${DB_NAME}
   - DB_USER=${DB_USER}
   - DB_USER_PASSWORD=${DB_USER_PASSWORD}
   - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
   - WP_TITLE=${WP_TITLE}
   - WP_URL=${WP_URL}
   - WP_USER=${WP_USER}
   - WP_USER_MAIL=${WP_USER_MAIL}
   - WP_USER_PASSWORD=${WP_USER_PASSWORD}
   - WP_ADMIN=${WP_ADMIN}
   - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
   - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
  restart: unless-stopped
