FROM debian:buster

RUN apt-get update -y

RUN apt-get install mariadb-server
#RUN mysql_secure_installation
#RUN systemctl status mariadb
# Create Database and User
#	RUN mysql -u root -p
#	RUN CREATE DATABASE wordpress_database;
#	RUN CREATE USER 'username'@'localhost' IDENTIFIED BY 'password';
#	RUN GRANT ALL PRIVILEGES ON * . * TO 'username'@'localhost';
#	RUN FLUSH PRIVILEGES;
#Exit MariaDB by pressing Ctrl–d.